- name: Build base images
  shell: "docker build -t whanos-{{ item }}:latest - < {{ playbook_dir }}/../images/{{ item }}/Dockerfile.base"
  loop:
    - c
    - java
    - javascript
    - python
    - befunge
    - typescript
    - go
    - rust
    - ruby
    - php
    - csharp
