FROM maven:3.9-eclipse-temurin-21
SHELL ["/bin/bash", "-c"]

WORKDIR /app
ONBUILD COPY . .
ONBUILD RUN mvn package -q && cp target/*.jar app.jar && rm -rf target src pom.xml

CMD ["java", "-jar", "app.jar"]
