FROM php:8.3-cli
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y unzip && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ONBUILD COPY . .
ONBUILD RUN composer install --no-dev --optimize-autoloader

EXPOSE 8080
CMD ["php", "-S", "0.0.0.0:8080", "-t", "app"]
