FROM node:20.9
SHELL ["/bin/bash", "-c"]

WORKDIR /app
COPY package.json tsconfig.json ./
RUN npm install && npm install -g typescript
COPY . .
RUN tsc && find . -name "*.ts" -type f -not -path "./node_modules/*" -delete

EXPOSE 8080
CMD ["node", "."]
